//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbContact
    {
        public int ID { get; set; }
        public string Sname { get; set; }
        public string Semail { get; set; }
        public string Smsg { get; set; }
    }
}
